### ISSUE TITLE
[Setup] - Dựng hạ tầng Server Vphere.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#11]

**Comment by lamsd** [comment]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
Chuẩn bị: Máy chủ mạnh, ổ cứng, mạng.
Cài ESXi: Trên mỗi máy chủ, tạo nền tảng chạy máy ảo.
Cài vCenter: Quản lý tập trung, một máy ảo riêng.
Kết nối mạng: vSwitch, VLAN 
Cấu hình storage: Nơi chứa máy ảo, chia datastore.
Tạo máy ảo: Cấp CPU, RAM, cài hệ điều hành.
