### ISSUE TITLE
[Setup] - Dựng máy ảo server Linux.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#12]

**Comment by lamsd** [comment]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
Chuẩn bị: File ISO Linux, tài nguyên (CPU, RAM).
Tạo máy ảo: Chọn ESXi, datastore, gắn ISO.
Cài Linux: Như máy thật, phân vùng, mạng...
Cài VMware Tools: Tối ưu, tích hợp vSphere.
