### ISSUE TITLE
[Setup] - Cấu hình hạ tầng máy ảo NAS.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#13]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
1. Chuẩn bị:

Tải file ISO Xpenology: Tìm bản tương thích với phần cứng máy chủ ESXi và phiên bản vSphere của bạn. Các diễn đàn như xpenology.com có thể giúp bạn tìm bản phù hợp.
Tài nguyên máy ảo: Cấp phát CPU, RAM, ổ cứng ảo đủ cho Xpenology hoạt động. RAM tối thiểu 2GB, ổ cứng tối thiểu 8GB, nên dùng ổ cứng ảo dạng thin provision để tiết kiệm dung lượng.
2. Tạo máy ảo:

Trong vCenter, tạo máy ảo mới trên ESXi host.
Chọn hệ điều hành "Other Linux".
Gắn file ISO Xpenology vào ổ CD/DVD ảo.
Thêm ổ cứng ảo thứ hai, chọn file image ổ cứng ảo đã chuẩn bị ở bước 1.
Quan trọng: Trong phần thiết bị, thêm một ổ đĩa mềm ảo và kết nối với file image "synoboot.img" (thường có trong bộ cài Xpenology).
3. Cài đặt Xpenology:

Khởi động máy ảo.
Trong BIOS của máy ảo, thiết lập boot từ ổ đĩa mềm.
Máy ảo sẽ khởi động từ "synoboot.img" và bắt đầu quá trình cài đặt.
Sử dụng Synology Assistant (trên máy tính khác) để tìm và kết nối đến NAS Xpenology.
Làm theo hướng dẫn để hoàn tất cài đặt Xpenology.
4. Sau khi cài đặt:

Cấu hình mạng cho Xpenology, bao gồm IP tĩnh 
Cài đặt các dịch vụ NAS như chia sẻ file, media server...
