### ISSUE TITLE
[Setup] - Cấu hình máy ảo Server Window.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#14]

**Comment by lamsd** [comment]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
Chuẩn bị: File ISO Windows Server, license key, tài nguyên (CPU, RAM, ổ cứng).
Tạo máy ảo: Chọn ESXi, datastore, gắn ISO.
Cài Windows: Boot từ ISO, phân vùng, cài đặt.
Cài VMware Tools: Tối ưu, tích hợp vSphere.
