### ISSUE TITLE
[Setup] - Cấu hình DDNS truy cập server.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#15]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
Cấu hình DDNS truy cập server Vphere

Tạo tài khoản & hostname trên No-IP: Đăng ký, tạo hostname, trỏ tới IP server.
Cài DUC: Trên server, đăng nhập, chọn hostname để tự động cập nhật IP.
Cấu hình router (nếu cần): Forward port dịch vụ tới IP local của server.
Kiểm tra: Truy cập server qua hostname.

**Comment by lamsd** [comment]
Okie
