### ISSUE TITLE
[Setup] - Cấu hình triển khai dịch vụ trên Vphere.

### ISSUE THREAD

**Issue by lamsd** [UTH-Master/setup_system#16]
Cần ghi rõ thông tin và quá trình làm

**Comment by TuanHoangDinh** [comment]
Phân quyền:

Tạo nhóm người dùng: Trong vCenter, tạo các nhóm người dùng với quyền truy cập khác nhau (ví dụ: quản trị viên, người dùng).
Phân quyền cho VM: Gán quyền cho các nhóm người dùng trên các VM và tài nguyên (ví dụ: quyền truy cập, quyền quản lý).
Phân quyền cho vCenter: Phân quyền truy cập vào các chức năng của vCenter (ví dụ: tạo VM, quản lý mạng).
 Snapshot tự động:

Sử dụng vCenter: Lên lịch tạo snapshot tự động cho các VM quan trọng.
Cấu hình: Chọn tần suất (hàng ngày, hàng tuần), thời gian, số lượng snapshot lưu trữ.
Lưu ý: Snapshot chiếm dung lượng lưu trữ, cần quản lý và xóa định kỳ.
Tự động cân bằng tải (DRS):

Bật DRS cluster: Tạo cluster DRS trong vCenter, thêm các host ESXi vào cluster.
Cấu hình DRS rules: Định nghĩa các quy tắc để DRS tự động di chuyển VM giữa các host nhằm cân bằng tải.
Theo dõi hiệu năng: vCenter sẽ theo dõi hiệu năng của các host và VM, tự động di chuyển VM khi cần thiết.
Gửi cảnh báo email:

Cấu hình vCenter alarms: Tạo alarms trong vCenter để theo dõi các sự kiện (ví dụ: CPU usage cao, dung lượng đĩa thấp).
Cấu hình email settings: Trong vCenter, cấu hình server SMTP, tài khoản email để gửi cảnh báo.

**Comment by lamsd** [comment]
Done
